STRING

In [1]:
string = 'hello twilearn'

In [4]:
a = string.capitalize() #First letter of the each sentance will become captial
print(a)

Hello twilearn


In [6]:
string1 = 'I am from India and born in Tamilnadu, India'
b = string1.count('India')
print(b)

2


In [7]:
string2 = 'I love apples, apple are my favorite fruit'
c = string2.find('banana')
c

-1

In [9]:
d=string2.find('apple')
d

7

## Module 3

For Loop

        it is used for iterating over a squence (that is either a list a tuple a dictionary, a set or a string).
        using Break & continue keyword

In [1]:
fruit=['apple', 'banana', 'cherry','pinapple','orange']
for i in fruit:
    print(i)

apple
banana
cherry
pinapple
orange


In [6]:
for x in fruit:
    print(x)
    if x=='banana':
        break

apple
banana


In [9]:
for x in fruit:
    if x=='cherry':
        continue
    print(x)

apple
banana
pinapple
orange


While Loop

        with the while loop we can execute a set of statements as long as condition is true.
        
        using Break continue keyword

In [10]:
num = 1

while num < 11:
    print(num)
    num += 1

1
2
3
4
5
6
7
8
9
10


In [11]:
num = 1

while num < 6:
    print(num)
    if num == 5:
        break
    num += 1

1
2
3
4
5


In [2]:
num = 0

while num < 10:
    num += 1
    if num == 5:
        continue
    print(num)

1
2
3
4
6
7
8
9
10


Function

    A Function is block of code which only runs when it is called
    Advanced Function - Lambda, map, zip

In [3]:
def my_function():
    print(' Hello im from a function')

In [4]:
my_function()

 Hello im from a function


In [5]:
def  my_ID(name):
    print('CR00' + name)

my_ID('Hari')

CR00Hari


In [6]:
def add(a, b, c):
    return (a+b+c)

add(4,5,9)

18

    we can do this by using Lambda function

In [8]:
add = lambda a,b,c: print (a+b+c)
add(4,9,5)

18


Map Function

In [10]:
n = [1,2,3,4,5]

def sq(n):
    return n*n

square = map(sq,n)

print(list(square))

[1, 4, 9, 16, 25]


Zip function

In [13]:
name = ['hari'.upper(),'Krishna','Ram']

ID = [1, 2, 3]

mapped = (zip(name, ID))

print(list(mapped))

[('HARI', 1), ('Krishna', 2), ('Ram', 3)]


## Tuple, Dictionary and Set

Tuple

    They are used to store multiple items in a single variable.
    A tuple is a collection which is ordered and unchangeable. It is written with round brackets

In [1]:
fruits = ('apple', 'banana', 'cherru')
print(fruits)

('apple', 'banana', 'cherru')


In [2]:
fruits = ('apple', 'banana', 'cherru','banana')
print(fruits)

('apple', 'banana', 'cherru', 'banana')


In [3]:
# count() methods

nums = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)

nums.count(5)

2

In [4]:
# index() method

nums = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)

nums.index(5)

5

In [5]:
# min() & max() method


nums = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)

min(nums)

1

In [6]:
max(nums)

8

Dictionary

    Dictionaries are used to store data values in key:value pairs.
    A dictionary is collectyion which is ordered*, changeable and do not allow duplicates.

In [7]:
car = {'brand': 'Ford','model':'Mustang','year':1964}

In [8]:
# get() method

car.get('model')

'Mustang'

In [9]:
# items() method

car.items()

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])

In [11]:
#keys() method

car.keys()

dict_keys(['brand', 'model', 'year'])

In [14]:
# values() method

car.values()

dict_values(['Ford', 'Mustang', 1964])

In [15]:
# pop() method

car.pop('model')
print(car)

{'brand': 'Ford', 'year': 1964}


In [16]:
# popitem() method

car.popitem()
print(car)

{'brand': 'Ford'}


In [18]:
car = {'brand': 'Ford','model':'Mustang','year':1964}

In [20]:
# update() method

car.update({'color': 'red'})
print(car)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}


In [21]:
#clear() method

car.clear()
print(car)

{}


### set

    sets are used to store multiple items in a single variable
    sets are written with curly brackets

In [25]:
fruits = {'apple', 'banana', 'cherry'}

In [27]:
# add()

fruits.add('orange')
print(fruits)

{'cherry', 'apple', 'banana', 'orange'}


In [28]:
fruits.pop()
print(fruits)

{'apple', 'banana', 'orange'}


In [29]:
# remove

fruits.remove('banana')
print(fruits)

{'apple', 'orange'}


In [31]:
x = {'apple', 'banana', 'cherry'}

y = {'google', 'microsoft', 'apple'}

# difference

print(x.difference(y))

{'cherry', 'banana'}


In [32]:
# intersection

print(x.intersection(y))

{'apple'}


In [33]:
# union

print(x.union(y))

{'cherry', 'microsoft', 'apple', 'banana', 'google'}


In [34]:
# update

x.update(y)
print(x)

{'cherry', 'microsoft', 'apple', 'banana', 'google'}


# Data science

### Numpy

In [1]:
# importing numpy library
import numpy as np

In [4]:
a = np.array(5)
a

array(5)

In [5]:
np.ndim(a)

0

In [6]:
one = np.array([1,2,3,4,5])
two = np.array([[1,2,3],[4,5,6]])
three = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
print(one)

[1 2 3 4 5]


In [7]:
np.ndim(one)

1

In [11]:
print(two)

[[1 2 3]
 [4 5 6]]


In [8]:
np.ndim(two)

2

In [12]:
print(three)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
np.ndim(three)

2

In [13]:
three_D = np.array([[1,2,3],[4,5,6],[7,8,9],[1,4,7]])
print(three_D)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 4 7]]


In [14]:
np.ndim(three_D)

2

In [16]:
three_D1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,4,7]]])
print(three_D1)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 4 7]]]


In [17]:
np.ndim(three_D1)

3

### List Vs Array

In [18]:
list1 = [1,2.0,'apple']     #List allow Different Data types
arr = np.array([1,2,3,4,5]) #Array  doesn't allow different data types

In [22]:
arr1 = np.array([1,2,3,5,2.0,'apple'])   # type conversion

In [23]:
arr1

array(['1', '2', '3', '5', '2.0', 'apple'], dtype='<U32')

#### More advantage of numpy array over list

        Array consumes less memory
        array are faster than lists

Numpy Reshaping & indexing